name: BACKSEAT Co.
favicon: null
layout_spectrum: 0.16612
typography_spectrum: 0.377551
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: the BACKSEAT company
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.9375
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose:
  - name: follow
    url: null
    item: null
